import Card from '@/components/Card'

export default function Page() {
  const recs = [
    { id: 1, title: 'Automate host isolation via EDR API', severity: 'High' },
    { id: 2, title: 'Add tabletop schedule for containment scenarios', severity: 'Medium' },
    { id: 3, title: 'Improve log retention for cloud audit events', severity: 'Medium' },
  ]

  return (
    <div className="space-y-8">
      <header>
        <h1 className="h1">Recommendations</h1>
        <p className="text-muted mt-2">Prioritized improvements generated by IRIS</p>
      </header>

      <Card>
        <ul className="divide-y divide-neutral-200">
          {recs.map(r => (
            <li key={r.id} className="py-4 flex items-center justify-between">
              <div className="font-medium">{r.title}</div>
              <span className="badge">{r.severity}</span>
            </li>
          ))}
        </ul>
      </Card>
    </div>
  )
}
